# Generated by Django 3.0.3 on 2020-06-09 18:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clioncare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_json_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('gender', models.CharField(max_length=10)),
                ('hair_color', models.CharField(max_length=25)),
                ('baldness_pattern', models.CharField(max_length=30)),
                ('had_transplant', models.CharField(max_length=30)),
                ('problem_since', models.IntegerField()),
                ('how_bad', models.CharField(max_length=50)),
                ('urgency', models.CharField(max_length=50)),
                ('fullname', models.CharField(max_length=80)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('mob_no', models.IntegerField()),
            ],
        ),
    ]
