# Generated by Django 3.0.3 on 2020-06-09 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clioncare', '0003_auto_20200610_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='baldness_pattern',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mob_no',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='patient',
            name='problem_since',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='urgency',
            field=models.CharField(max_length=60),
        ),
    ]
