# Generated by Django 3.0.3 on 2020-06-13 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clioncare', '0005_remove_patient_raw_json_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='profile_image',
            field=models.ImageField(default='', upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='email address'),
        ),
    ]
