# Generated by Django 3.0.3 on 2020-06-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clioncare', '0006_auto_20200613_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='email address'),
        ),
    ]
