# Generated by Django 3.0.3 on 2020-06-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clioncare', '0007_auto_20200613_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
