# Generated by Django 3.0.3 on 2020-06-13 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clioncare', '0008_auto_20200613_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usermessage',
            name='email',
        ),
    ]
