# Generated by Django 3.0.3 on 2020-06-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clioncare', '0009_auto_20200613_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.CharField(default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermessage',
            name='email',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
